on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: R-shield

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    if: "!contains(github.event.head_commit.message, 'skip shield')"

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SLACK_API_TEST_MODE: false

    steps:
      - uses: actions/checkout@main

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install shield dependencies
        run: |
          install.packages('remotes')
          remotes::install_github('yonicd/shield')
          shield::install_remotes(shield::create_map())
          remotes::install_local(force = TRUE, upgrade = TRUE)
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

      - name: slackteams trigger
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: yonicd/slackteams
          event-type: push
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: slackthreads trigger
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: yonicd/slackthreads
          event-type: push
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: slackposts trigger
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: yonicd/slackposts
          event-type: push
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
